preload = ~/Pictures/wallpapers/1075646.jpg

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/1075646.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/1075646.jpg
    fit_mode = cover
}

splash = false 
